version: "3.3"
services:
  nginx:
    container_name: ${COMPOSE_PROJECT_NAME}_nginx
    image: nginx
    working_dir: '/var/www'
    volumes:
     - ./.docker/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
     - ./.docker/nginx/logs/:/var/log/nginx:rw
     #project
     - ./app:/var/www:ro
    depends_on:
     - php
    ports:
     - ${NGINX_PORT}:80

  php:
    container_name: ${COMPOSE_PROJECT_NAME}_php
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    stop_signal: INT
    working_dir: '/var/www'
    depends_on:
      - redis
      - mysql
    volumes:
    #config
      #fpm
      - ./.docker/php/conf/fpm/php-fpm.conf:/etc/php/7.2/fpm/php-fpm.conf:ro
      - ./.docker/php/conf/fpm/pool.d:/etc/php/7.2/fpm/pool.d:ro
      - ./.docker/php/conf/fpm/php.ini:/etc/php/7.2/fpm/php.ini:ro

      #modules
      - ./.docker/php/conf/mods-available/xdebug.ini:/etc/php/7.2/mods-available/xdebug.ini:ro

      #logs
      - ./.docker/php/logs/php:/var/log/php:rw
      #debug TODO!
      #- ./.docker/php/debug:/var/log/php-debug

      - ~/.composer/cache:/root/.composer/cache:rw
      - ~/.composer/auth.json:/root/.composer/auth.json:rw
#      - ~/.ssh:/root/.ssh:ro

      - ./app:/var/www:rw


      - ./.docker/php/conf/supervisor/:/etc/supervisor/conf.d/:ro
    env_file:
      - .env
    environment:
      XDEBUG_CONFIG: "remote_host=${COMPOSE_DEVELOPER_IP}"
      PHP_IDE_CONFIG: "serverName=${COMPOSE_PROJECT_NAME}"

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}_mysql
    image: percona:5.7
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --init-connect='SET NAMES UTF8MB4;' --innodb-flush-log-at-trx-commit=0
    volumes:
     - ./.docker/mysql/config/my.cfg:/etc/mysql/my.cnf:ro
     - ./.docker/mysql/initdb/:/docker-entrypoint-initdb.d/:ro
#     - ./.docker/mysql/data:/var/lib/mysql:rw
     - ./.docker/mysql/logs:/var/log/mysql:rw
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - ${MYSQL_PORT}:3306

  redis:
    container_name: ${COMPOSE_PROJECT_NAME}_redis
    image: redis:4
    command: 'redis-server /usr/local/etc/redis/redis.conf'
    volumes:
      - ./.docker/redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
      - ./.docker/redis/data:/data:rw
    ports:
      - ${REDIS_PORT}:6379